workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Initialize Android Project
        script: |
          # إنشاء ملفات الأندرويد المفقودة مباشرة في السيرفر
          flutter create . --platforms android --org com.cardiachat
          
          # إعادة حقن ملف الفايربيس الذي أرسلته لي
          mkdir -p android/app
          echo '{
            "project_info": {
              "project_number": "611649500085",
              "project_id": "cardiachat",
              "storage_bucket": "cardiachat.firebasestorage.app"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:611649500085:android:cd3d42d47cc8a18fff5ffc",
                  "android_client_info": { "package_name": "com.cardiachat.app" }
                },
                "api_key": [{ "current_key": "AIzaSyA8pKFisH9v9YB6O8YkHerO5s27FqviE6g" }]
              }
            ],
            "configuration_version": "1"
          }' > android/app/google-services.json

      - name: Get Flutter packages
        script: flutter packages pub get
        
      - name: Build Android APK
        script: |
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - almwldahmed199@gmail.com
