workflows:
  android-release:
    name: Android Release Build (Target 20MB)
    max_build_duration: 15
    instance_type: mac_mini_m2
    environment:
      groups:
        - default
    scripts:
      - name: Clean and Get Dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build and Shrink APK
        script: |
          flutter build apk --release --split-per-abi --tree-shake-icons --android-skip-build-dependency-validation
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - almwldahmed199@gmail.com
