workflows:
  android-release:
    name: Android Release Build (Target 20MB)
    max_build_duration: 15
    instance_type: mac_mini_m1
    scripts:
      - name: Build and Shrink APK
        script: | 
          flutter build apk --release --split-per-abi --tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - almwldahmed199@gmail.com
