workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Install dependencies
        script: flutter packages pub get
      - name: Build Android APK
        script: | 
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - almwldahmed199@gmail.com
